# Generated by Django 2.2.11 on 2020-08-09 08:15

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=50)),
                ('tz', timezone_field.fields.TimeZoneField(default='Asia/Kolkata')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FullThrottleApp.Employee')),
            ],
        ),
    ]
